name: build project
on:
    push:
        branches:
            - main
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
            - name: setup pnpm
              uses: pnpm/action-setup@v4
            - name: setup node
              uses: actions/setup-node@v4
              with:
                node-version: 22
                cache: 'pnpm'
            - name: install dependencies
              run: pnpm install
            - name: run unit tests
              run: pnpm run test:unit
    type-check:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
            - name: setup pnpm
              uses: pnpm/action-setup@v4
            - name: setup node
              uses: actions/setup-node@v4
              with:
                node-version: 22
                cache: 'pnpm'
            - name: install dependencies
              run: pnpm install
            - name: run type check
              run: pnpm run type-check
    build:
        needs:
            - type-check
            - test
        runs-on: ubuntu-latest
        steps:
          - name: checkout repo
            uses: actions/checkout@v4
          - name: setup pnpm
            uses: pnpm/action-setup@v4
          - name: setup node
            uses: actions/setup-node@v4
            with:
              node-version: 22
              cache: 'pnpm'
          - name: install dependencies
            run: pnpm install
          - name: build app
            run: pnpm run build:only
          - name: upload build results
            uses: actions/upload-artifact@v4
            if: always()
            with:
              name: dist
              path: dist/**
              retention-days: 30
    release:
        permissions:
            contents: write
            issues: write
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
            - name: setup pnpm
              uses: pnpm/action-setup@v4
            - name: setup node
              uses: actions/setup-node@v4
              with:
                node-version: 22
                cache: 'pnpm'
            - name: create release
              run: pnpm dlx semantic-release
              env:
                GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
