name: build
on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
            - name: setup pnpm
              uses: pnpm/action-setup@v4
            - name: setup node
              uses: actions/setup-node@v4
              with:
                node-version: 22
                cache: 'pnpm'
            - name: install dependencies
              run: pnpm install
            - name: run playwrigth test
              run: pnpm dlx playwright install --with-deps
            - name: run unit tests
              run: pnpm run test:unit
            - name: run type check
              run: pnpm run type-check
            - name: checkout repo
              uses: actions/checkout@v4
            - name: setup pnpm
              uses: pnpm/action-setup@v4
            - name: setup node
              uses: actions/setup-node@v4
              with:
                node-version: 22
                cache: 'pnpm'
            - name: install dependencies
              run: pnpm install
            - name: build app
              run: pnpm run build:only
            - name: create release
              run: pnpm dlx semantic-release
              env:
                  GITHUB_TOKEN: ${{secrets.SEMANTIC_RELEASE_TOKEN}}
