name: run playwrigth tests
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    e2e-test:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
            - name: setup pnpm
              uses: pnpm/action-setup@v4
            - name: setup node
              uses: actions/setup-node@v4
              with:
                node-version: 22
                cache: 'pnpm'
            - name: install dependencies
              run: pnpm install
            - name: run playwrigth test
              run: pnpm dlx playwright install --with-deps
            - name: upload test results
              uses: actions/upload-artifact@v4
              if: always()
              with:
                name: playwright-report
                path: playwright-report/**
                retention-days: 30

            
